// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"net/http"
	"speech-api/internal/handler"
	"speech-api/internal/pkg/httpclient"
	"speech-api/internal/service/transcribe"
	"speech-api/internal/websocket"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeServer() *http.Server {
	httpClient := httpclient.NewHttpClient()
	transcribeService := transcribe.NewTranscribeService(httpClient)
	webSocketPool := websocket.NewWebSocketPool()
	stream := handler.NewStream(transcribeService, webSocketPool)
	server := NewServer(httpClient, stream)
	return server
}
